-- Tabela para armazenar o estado do nosso indexador
CREATE TABLE IF NOT EXISTS public.indexer_state (
  id BIGINT PRIMARY KEY,
  last_checked_block BIGINT NOT NULL
);

-- Garante que a linha de estado do nosso indexador exista
-- Usamos um ID fixo (1) para o estado do indexador EVM
INSERT INTO public.indexer_state (id, last_checked_block) VALUES (1, 0) ON CONFLICT (id) DO NOTHING;

-- Tabela para armazenar as mensagens encontradas na blockchain
CREATE TABLE IF NOT EXISTS public.messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMPTZ DEFAULT NOW() NOT NULL,
  recipient TEXT NOT NULL,
  sender TEXT NOT NULL,
  content TEXT, -- Conteúdo da mensagem, decodificado do IPFS
  tx_hash TEXT UNIQUE NOT NULL, -- Hash da transação on-chain, para evitar duplicatas
  cid TEXT, -- O ponteiro para o conteúdo no IPFS
  network TEXT -- A rede onde a mensagem foi encontrada (ex: arbitrum_sepolia)
);

-- Habilita a Realtime para a tabela de mensagens, se desejado
-- Isso permitiria que a UI recebesse novas mensagens em tempo real
-- supabase extensions enable pgsodium
-- alter publication supabase_realtime add table messages;
